import React from "react";
import { Link } from "react-router-dom";
import { HiOutlineArrowLeft } from "react-icons/hi";

const Table4 = () => {
  return (
    <>
     <section className="content-table home-wrapper-2">
      <div className="container-xxl">
        <div className="row" data-aos="fade-down" data-aos-delay="300">
          <h2>TAXATION & REVENUE CATEGORY OF SERVICES</h2>
          <div className="col-12">
            <table class="tab_ca">
              <tbody>
                <tr>
                  <td class="cell_ca_head_dx_dbr">
                    <p class="ca_head_title_wt">Avenue of Services</p>
                  </td>
                  <td class="cell_ca_head_dgr">
                    <p class="ca_head_title_wt">Descriptive Outline</p>
                  </td>
                </tr>
                <tr>
                  <td class="cell_ca_dx_lbr">
                    <a href="">
                      <p class="des_title_dbr">
                        Business Tax Planning Services
                      </p>
                    </a>
                  </td>
                  <td class="cell_blank_des_lgr">
                    <p class="tax_text">
                      Business tax planning is the analysis of a financial
                      situation or strategy from a taxation standpoint, the
                      persistence of tax planning is to ensure the tax
                      efficiency and through tax planning, all foundations of
                      the financial strategy work together in the most
                      tax-friendly manner possible.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td class="cell_ca_dx_lbr">
                    <a href="">
                      <p class="des_title_dbr">Customs Law Services</p>
                    </a>
                  </td>
                  <td class="cell_blank_des_lgr">
                    <p class="tax_text">
                      Customs law is a duty, tax, charges, or imposts levied by
                      the government on imported or exported goods, customs duty
                      is applied to the movement of goods irrespective of sales
                      or purchase, it is a tax which is applied indirectly by
                      government, applicable only on goods and not on services.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td class="cell_ca_dx_lbr">
                    <a href="">
                      <p class="des_title_dbr">Federal Excise Law Services</p>
                    </a>
                  </td>
                  <td class="cell_blank_des_lgr">
                    <p class="tax_text">
                      Federal excise law is a legislated duty on specific goods
                      or services at purchase such as tobacco, cement,
                      automobiles and liquified natural gas, excise duties are
                      intranational duties imposed within a government
                      infrastructure rather than international duties imposed
                      across country borders.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td class="cell_ca_dx_lbr">
                    <a href="">
                      <p class="des_title_dbr">Income Tax Law Services</p>
                    </a>
                  </td>
                  <td class="cell_blank_des_lgr">
                    <p class="tax_text">
                      Income tax law signifies a type of tax that governments
                      impose on income generated by individuals and businesses
                      within their jurisdiction, income taxes are a source of
                      revenue for governments as these are used to fund public
                      services, fulfil governmental commitments and facilitate
                      the people.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td class="cell_ca_dx_lbr">
                    <a href="">
                      <p class="des_title_dbr">Income Tax Rates</p>
                    </a>
                  </td>
                  <td class="cell_blank_des_lgr">
                    <p class="tax_text">
                      Income tax rates describing the percentage at which
                      individuals or corporate entities are taxed, in Pakistan
                      the Federal Board of Revenue (FBR) uses an unconventional
                      tax rate system, in which the percentage of tax charged
                      increases as the amount of the person's or entity's
                      taxable income increases.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td class="cell_ca_dx_lbr">
                    <a href="">
                      <p class="des_title_dbr">Income Tax Refund Services</p>
                    </a>
                  </td>
                  <td class="cell_blank_des_lgr">
                    <p class="tax_text">
                      Income tax refund is a reimbursement to a taxpayer of any
                      excessive amount paid to the federal or a provincial
                      government, taxpayers tend to look at a refund as a bonus
                      or a stroke of luck, but it most often represents an
                      interest-free loan that the taxpayer made to the
                      government.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td class="cell_ca_dx_lbr">
                    <a href="">
                      <p class="des_title_dbr">Income Tax Returns Services</p>
                    </a>
                  </td>
                  <td class="cell_blank_des_lgr">
                    <p class="tax_text">
                      Income tax returns are the forms in which assessees file
                      information about their income and tax thereon before the
                      income tax department, if anyone files a belated return,
                      he / she would not be allowed to carry forward certain
                      losses, resultantly you’re required to file a tax return
                      every year, through this process.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td class="cell_ca_dx_lbr">
                    <a href="">
                      <p class="des_title_dbr">
                        International Tax Law Services
                      </p>
                    </a>
                  </td>
                  <td class="cell_blank_des_lgr">
                    <p class="tax_text">
                      International tax law is applicable to the taxing of
                      activity that takes place in two or more countries in form
                      of international tax agreements between two or more
                      countries, are also known as income tax treaties, or tax
                      conventions or double taxation agreements or DTAs.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td class="cell_ca_dx_lbr">
                    <a href="">
                      <p class="des_title_dbr">Payroll Services</p>
                    </a>
                  </td>
                  <td class="cell_blank_des_lgr">
                    <p class="tax_text">
                      Payroll service provider is a firm or organization that
                      automatically processes payroll calculations, payroll tax
                      statements, year-end taxes and more, many employers prefer
                      to use payroll service providers to help ensure their
                      employees and taxes are paid timely and accurately.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td class="cell_ca_dx_lbr">
                    <a href="">
                      <p class="des_title_dbr">Sales Tax Law Services</p>
                    </a>
                  </td>
                  <td class="cell_blank_des_lgr">
                    <p class="tax_text">
                      Sales Tax is a form of tax paid to a governing body for
                      the sale of goods and services, sales tax is an indirect
                      tax and is generally charged at the point of purchase or
                      exchange of certain taxable goods, charged as a percentage
                      of the value of the product.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td class="cell_ca_dx_lbr">
                    <a href="">
                      <p class="des_title_dbr">Sales Tax Refund Services</p>
                    </a>
                  </td>
                  <td class="cell_blank_des_lgr">
                    <p class="tax_text">
                      Sales tax refund can be described as if a registered
                      person has overpaid sales tax because of error, he / she
                      may request a refund of the overpaid amount from the
                      relevant tax authorities within a year after the payment
                      for which a claim is made.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td class="cell_ca_dx_lbr">
                    <a href="">
                      <p class="des_title_dbr">Sales Tax Returns Services</p>
                    </a>
                  </td>
                  <td class="cell_blank_des_lgr">
                    <p class="tax_text">
                      Sales tax return is the taxpayer's document of declaration
                      through which taxpayer not only furnishes the details of
                      transactions during a tax period but also deposits his
                      sales tax liability.
                    </p>
                  </td>
                </tr>
              </tbody>
            </table>
            <p className="table-end">
              <strong>
                <a>Table: </a>Business &amp; Taxation & Revenue Category of
                Services
              </strong>
            </p>
            <Link to="/" className="d-flex align-items-center gap-15">
                  <HiOutlineArrowLeft className="fs-4" />
                  Go Back To Home
                </Link>
          </div>
        </div>
      </div>
      </section>
    </>
  );
};

export default Table4;
